<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CertificateDiscovery.Domain\CertificateDiscovery.Domain.csproj" />
    <ProjectReference Include="..\CertificateDiscovery.Application\CertificateDiscovery.Application.csproj" />
    <ProjectReference Include="..\CertificateDiscovery.Infrastructure\CertificateDiscovery.Infrastructure.csproj" />
    <ProjectReference Include="..\CertificateDiscovery.Contracts\CertificateDiscovery.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
