// <auto-generated />
using System;
using CertificateDiscovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertificateDiscovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CertificateDiscoveryDbContext))]
    [Migration("20260715221025_AddAuthenticationUsers")]
    partial class AddAuthenticationUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextScanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SniHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port", "Protocol");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AssetCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentlyActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservedChainPosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("IsCurrentlyActive");

                    b.HasIndex("AssetId", "CertificateId");

                    b.ToTable("AssetCertificates");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelfSigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PemEncodedCertificate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicKeySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FingerprintSha256")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateSubjectAlternativeName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId", "Name", "Type")
                        .IsUnique();

                    b.ToTable("CertificateSubjectAlternativeNames");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJobAsset", b =>
                {
                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("ScanJobId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("ScanJobAssets");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CipherSuite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDiagnosticData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsProtocol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ScanJobId");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.WorkerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedJobCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("WorkerName")
                        .IsUnique();

                    b.ToTable("WorkerNodes");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AssetCertificate", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetCertificates")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany("AssetCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateSubjectAlternativeName", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany("SubjectAlternativeNames")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJobAsset", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("Assets")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanResult", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany("ScanResults")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("CertificateDiscovery.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("Results")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Certificate");

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetCertificates");

                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("AssetCertificates");

                    b.Navigation("SubjectAlternativeNames");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJob", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
