// <auto-generated />
using System;
using CertificateDiscovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertificateDiscovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CertificateDiscoveryDbContext))]
    [Migration("20260728212100_AddAgentDeploymentJobs")]
    partial class AddAgentDeploymentJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountKeySecretReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountLocation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AcmeProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountBindingKeyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcmeProviderId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.ToTable("AcmeAccounts");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeAccountEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcmeAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AcmeProviderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcmeAccountId");

                    b.HasIndex("AcmeProviderId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("AcmeAccountEvents");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeCertificateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcmeAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcmeAccountKeyPem")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcmeOrderLocation")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AcmeProviderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePem")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePrivateKeyPem")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChallengeCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DnsProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsPublishError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsPublishStatus")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DnsPublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsTxtName")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsTxtValue")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullChainPem")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastRenewalRequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScheduleCheckAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastScheduleCheckMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastScheduleCheckStatus")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextScheduleCheckAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalCronExpression")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("RenewalThresholdDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RenewedFromRequestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScheduleCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StoredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAlternativeNames")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaultSecretPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcmeAccountId");

                    b.HasIndex("AcmeProviderId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("DnsProviderId");

                    b.HasIndex("Domain");

                    b.HasIndex("NextScheduleCheckAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("VaultServerId");

                    b.ToTable("AcmeCertificateRequests");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDomainPattern")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateProfile")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountBindingHmacKey")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountBindingHmacSecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAccountBindingKeyId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStaging")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcmeProviders");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AgentDeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CertificateDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentAgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedBundleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateDeploymentId")
                        .IsUnique();

                    b.HasIndex("DeploymentAgentId", "Status", "CreatedAtUtc");

                    b.ToTable("AgentDeploymentJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextScanAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SniHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port", "Protocol");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AssetCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentlyActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObservedChainPosition")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("IsCurrentlyActive");

                    b.HasIndex("AssetId", "CertificateId");

                    b.ToTable("AssetCertificates");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelfSigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PemEncodedCertificate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicKeySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FingerprintSha256")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateChainEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintSha256")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelfSigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PemEncodedCertificate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicKeyAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicKeySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureAlgorithm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("FingerprintSha256");

                    b.HasIndex("CertificateId", "Position")
                        .IsUnique();

                    b.ToTable("CertificateChainEntries");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackupReference")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateRequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentPolicyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeploymentTargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservedFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackStatus")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CertificateRequestId");

                    b.HasIndex("DeploymentPolicyId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("DeploymentTargetId", "CertificateId");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("CertificateDeployments");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateSubjectAlternativeName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId", "Name", "Type")
                        .IsUnique();

                    b.ToTable("CertificateSubjectAlternativeNames");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKeyPem")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("MachineName");

                    b.HasIndex("Status");

                    b.ToTable("DeploymentAgents");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentAgentRegistrationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegisteredAgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("DeploymentAgentRegistrationTokens");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateDeploymentId", "CreatedAtUtc");

                    b.ToTable("DeploymentAuditEvents");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimOwner")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateDeploymentId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc", "LeaseExpiresAtUtc");

                    b.ToTable("DeploymentJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutomaticDeployment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentWindow")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RollbackOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VerificationTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeploymentPolicies");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeploymentTargets");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DiscoveredEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CipherSuite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiscoveryJobId")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PromotedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolGuess")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDiagnosticData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReverseDnsName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsProtocol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("DiscoveryJobId");

                    b.HasIndex("PromotedAssetId");

                    b.HasIndex("DiscoveryJobId", "IpAddress", "Port")
                        .IsUnique();

                    b.ToTable("DiscoveredEndpoints");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DiscoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CertificateFoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedEndpointCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ports")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScannedEndpointCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEndpointCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("DiscoveryJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DnsProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessKeySecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiToken")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTokenSecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsAuthenticationMode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureAuthenticationMode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostedZoneId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheckAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHealthCheckError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHealthCheckStatus")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagedIdentityClientId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropagationPollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropagationTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroup")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleArn")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKeySecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionTokenSecretReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TtlSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DnsProviders");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessfulAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAssetCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("ScanJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJobAsset", b =>
                {
                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("ScanJobId", "AssetId");

                    b.HasIndex("AssetId");

                    b.ToTable("ScanJobAssets");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CipherSuite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDiagnosticData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedIpAddress")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScanJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsProtocol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ScanJobId");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.SecretRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Purpose");

                    b.ToTable("SecretRecords");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultDiscoveryJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetCreatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("CertificateFoundCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreateAssets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedSecretCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KvMountPath")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecretCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("VaultServerId");

                    b.ToTable("VaultDiscoveryJobs");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultDiscoveryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PromotedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAlternativeNames")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VaultDiscoveryJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("PromotedAssetId");

                    b.HasIndex("VaultDiscoveryJobId");

                    b.HasIndex("VaultDiscoveryJobId", "SecretPath")
                        .IsUnique();

                    b.ToTable("VaultDiscoveryResults");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImportPkiCertificates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PkiMountPath")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScanPublicEndpoint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VaultServers");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.WorkerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedJobCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeatAtUtc");

                    b.HasIndex("WorkerName")
                        .IsUnique();

                    b.ToTable("WorkerNodes");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeAccount", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.AcmeProvider", "AcmeProvider")
                        .WithMany("Accounts")
                        .HasForeignKey("AcmeProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcmeProvider");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeCertificateRequest", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.AcmeAccount", "AcmeAccount")
                        .WithMany()
                        .HasForeignKey("AcmeAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertificateDiscovery.Domain.Entities.AcmeProvider", "AcmeProvider")
                        .WithMany()
                        .HasForeignKey("AcmeProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertificateDiscovery.Domain.Entities.DnsProvider", "DnsProvider")
                        .WithMany()
                        .HasForeignKey("DnsProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertificateDiscovery.Domain.Entities.VaultServer", "VaultServer")
                        .WithMany()
                        .HasForeignKey("VaultServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcmeAccount");

                    b.Navigation("AcmeProvider");

                    b.Navigation("Certificate");

                    b.Navigation("DnsProvider");

                    b.Navigation("VaultServer");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AgentDeploymentJob", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.CertificateDeployment", "CertificateDeployment")
                        .WithMany()
                        .HasForeignKey("CertificateDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.DeploymentAgent", "DeploymentAgent")
                        .WithMany()
                        .HasForeignKey("DeploymentAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CertificateDeployment");

                    b.Navigation("DeploymentAgent");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AssetCertificate", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetCertificates")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany("AssetCertificates")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateChainEntry", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany("ChainEntries")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateDeployment", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.AcmeCertificateRequest", "CertificateRequest")
                        .WithMany()
                        .HasForeignKey("CertificateRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.DeploymentPolicy", "DeploymentPolicy")
                        .WithMany()
                        .HasForeignKey("DeploymentPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.DeploymentTarget", "DeploymentTarget")
                        .WithMany()
                        .HasForeignKey("DeploymentTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("CertificateRequest");

                    b.Navigation("DeploymentPolicy");

                    b.Navigation("DeploymentTarget");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.CertificateSubjectAlternativeName", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany("SubjectAlternativeNames")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentAuditEvent", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.CertificateDeployment", "CertificateDeployment")
                        .WithMany()
                        .HasForeignKey("CertificateDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateDeployment");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentJob", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.CertificateDeployment", "CertificateDeployment")
                        .WithMany()
                        .HasForeignKey("CertificateDeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificateDeployment");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DeploymentTarget", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DiscoveredEndpoint", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("CertificateDiscovery.Domain.Entities.DiscoveryJob", "DiscoveryJob")
                        .WithMany("Results")
                        .HasForeignKey("DiscoveryJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "PromotedAsset")
                        .WithMany()
                        .HasForeignKey("PromotedAssetId");

                    b.Navigation("Certificate");

                    b.Navigation("DiscoveryJob");

                    b.Navigation("PromotedAsset");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJobAsset", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("Assets")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanResult", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "Asset")
                        .WithMany("ScanResults")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId");

                    b.HasOne("CertificateDiscovery.Domain.Entities.ScanJob", "ScanJob")
                        .WithMany("Results")
                        .HasForeignKey("ScanJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Certificate");

                    b.Navigation("ScanJob");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultDiscoveryJob", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.VaultServer", "VaultServer")
                        .WithMany()
                        .HasForeignKey("VaultServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaultServer");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultDiscoveryResult", b =>
                {
                    b.HasOne("CertificateDiscovery.Domain.Entities.Certificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertificateDiscovery.Domain.Entities.Asset", "PromotedAsset")
                        .WithMany()
                        .HasForeignKey("PromotedAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertificateDiscovery.Domain.Entities.VaultDiscoveryJob", "VaultDiscoveryJob")
                        .WithMany("Results")
                        .HasForeignKey("VaultDiscoveryJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("PromotedAsset");

                    b.Navigation("VaultDiscoveryJob");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.AcmeProvider", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetCertificates");

                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("AssetCertificates");

                    b.Navigation("ChainEntries");

                    b.Navigation("SubjectAlternativeNames");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.DiscoveryJob", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.ScanJob", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("CertificateDiscovery.Domain.Entities.VaultDiscoveryJob", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
