<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CertificateDiscovery.Domain\CertificateDiscovery.Domain.csproj" />
    <ProjectReference Include="..\CertificateDiscovery.Application\CertificateDiscovery.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CertificateDiscovery.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.ResourceManager.Network" Version="1.10.0" />
    <PackageReference Include="Certes" Version="3.0.4" />
    <PackageReference Include="AWSSDK.Route53" Version="4.0.8.27" />
    <PackageReference Include="AWSSDK.CertificateManager" Version="4.0.2.15" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.2" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
    <PackageReference Include="Azure.ResourceManager" Version="1.13.0" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.8.0" />
    <PackageReference Include="Azure.ResourceManager.Dns" Version="1.1.1" />
    <PackageReference Include="DnsClient" Version="1.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="SSH.NET" Version="2025.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
