<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CertificateDiscovery.Domain\CertificateDiscovery.Domain.csproj" />
    <ProjectReference Include="..\CertificateDiscovery.Contracts\CertificateDiscovery.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
